### PR TITLE
User landing merge conflict fix

### PR DESCRIPTION
**Pull request by Zeebruh326**
For the last pull request, there was an issue with the app.jsx file.
This request pulled new changes and pushed changes in Landing branch.

### CODE REVIEW

**Comment by sarahabellard** [comment]
when i sign in as a user, i dont land on the land on the user landing page

**Review by sarahabellard — CHANGES_REQUESTED** [review]
make user landing the landing page after user signs in

**Comment by Zeebruh326** [comment]
> make user landing the landing page after user signs in

I have fixed the hrefs in both the userloginform file and the test file for userloginform.
Now should be good

**Comment by sarahabellard** [comment]
some buttons need to be changed:
ADD:
My Requests
My reservations
CHANGE:
Make payment -> view bills

**Review by sarahabellard — APPROVED** [review]

**Pull request merged**
